FROM nginx:alpine

# COPY index.html /usr/share/nginx/html
# COPY css /usr/share/nginx/html/css
# COPY js /usr/share/nginx/html/js
# docker build -t globant-2048 .
# docker run -v $(pwd)/index.html:/usr/share/nginx/html/index.html -v $(pwd)/css:/usr/share/nginx/html/css -v $(pwd)/js:/usr/share/nginx/html/js -p 5173:80 --rm globant-2048